name: Build APK ParkirGo

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_parkirgo

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'
          cache: true

      - name: Generate platform files
        run: |
          flutter create --project-name flutter_parkirgo --platforms android .
          # Force minSdkVersion 24 in build.gradle
          sed -i 's/minSdkVersion .*/minSdkVersion 24/g' android/app/build.gradle
          # Fix namespace issue if any
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK release
        run: flutter build apk --release --dart-define=BASE_URL=${{ vars.BASE_URL }}
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkirGo-APK
          path: flutter_parkirgo/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
